version: "3.5"

services:
  db:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Smena
      - POSTGRES_USER=Misfio32
    volumes:
      - type: bind
        source: /Users/ivanmamvriyskiy/Desktop/web/main/postgresData
        target: /mnt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 5

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  server:
    image: my-golang-server
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    depends_on:
      - server
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/access.log:/etc/nginx/access.log
      - ./nginx/error.log:/etc/nginx/error.log
      - ./nginx/html:/etc/nginx/html


  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=./mnt/swagger.yaml
    volumes:
      - ./main/swagger.yaml:/mnt/swagger.yaml
