port: "8000"

# db: 
#   username: "repl_user"
#   host: "postgres_replica_container"
#   port: "5432"
#   dbname: "postgres"
#   sslmode: "disable"

db: 
  username: "Misfio32"
  host: "postgres_container"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"