// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	pkg "github.com/Mamvriyskiy/database_course/main/pkg"
	gomock "github.com/golang/mock/gomock"
)

// MockIUserRepo is a mock of IUserRepo interface.
type MockIUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIUserRepoMockRecorder
}

// MockIUserRepoMockRecorder is the mock recorder for MockIUserRepo.
type MockIUserRepoMockRecorder struct {
	mock *MockIUserRepo
}

// NewMockIUserRepo creates a new mock instance.
func NewMockIUserRepo(ctrl *gomock.Controller) *MockIUserRepo {
	mock := &MockIUserRepo{ctrl: ctrl}
	mock.recorder = &MockIUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserRepo) EXPECT() *MockIUserRepoMockRecorder {
	return m.recorder
}

// AddCode mocks base method.
func (m *MockIUserRepo) AddCode(email pkg.EmailService) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCode", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCode indicates an expected call of AddCode.
func (mr *MockIUserRepoMockRecorder) AddCode(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCode", reflect.TypeOf((*MockIUserRepo)(nil).AddCode), email)
}

// ChangePassword mocks base method.
func (m *MockIUserRepo) ChangePassword(password, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", password, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockIUserRepoMockRecorder) ChangePassword(password, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockIUserRepo)(nil).ChangePassword), password, token)
}

// CreateUser mocks base method.
func (m *MockIUserRepo) CreateUser(user pkg.UserService) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIUserRepoMockRecorder) CreateUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIUserRepo)(nil).CreateUser), user)
}

// GetAccessLevel mocks base method.
func (m *MockIUserRepo) GetAccessLevel(userID, homeID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessLevel", userID, homeID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessLevel indicates an expected call of GetAccessLevel.
func (mr *MockIUserRepoMockRecorder) GetAccessLevel(userID, homeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessLevel", reflect.TypeOf((*MockIUserRepo)(nil).GetAccessLevel), userID, homeID)
}

// GetCode mocks base method.
func (m *MockIUserRepo) GetCode(token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCode", token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCode indicates an expected call of GetCode.
func (mr *MockIUserRepoMockRecorder) GetCode(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCode", reflect.TypeOf((*MockIUserRepo)(nil).GetCode), token)
}

// GetUser mocks base method.
func (m *MockIUserRepo) GetUser(email, password string) (pkg.UserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", email, password)
	ret0, _ := ret[0].(pkg.UserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockIUserRepoMockRecorder) GetUser(email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockIUserRepo)(nil).GetUser), email, password)
}

// GetUserByEmail mocks base method.
func (m *MockIUserRepo) GetUserByEmail(email string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", email)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockIUserRepoMockRecorder) GetUserByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockIUserRepo)(nil).GetUserByEmail), email)
}

// MockIHomeRepo is a mock of IHomeRepo interface.
type MockIHomeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIHomeRepoMockRecorder
}

// MockIHomeRepoMockRecorder is the mock recorder for MockIHomeRepo.
type MockIHomeRepoMockRecorder struct {
	mock *MockIHomeRepo
}

// NewMockIHomeRepo creates a new mock instance.
func NewMockIHomeRepo(ctrl *gomock.Controller) *MockIHomeRepo {
	mock := &MockIHomeRepo{ctrl: ctrl}
	mock.recorder = &MockIHomeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHomeRepo) EXPECT() *MockIHomeRepoMockRecorder {
	return m.recorder
}

// CreateHome mocks base method.
func (m *MockIHomeRepo) CreateHome(home pkg.HomeService) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHome", home)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHome indicates an expected call of CreateHome.
func (mr *MockIHomeRepoMockRecorder) CreateHome(home interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHome", reflect.TypeOf((*MockIHomeRepo)(nil).CreateHome), home)
}

// DeleteHome mocks base method.
func (m *MockIHomeRepo) DeleteHome(homeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHome", homeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHome indicates an expected call of DeleteHome.
func (mr *MockIHomeRepoMockRecorder) DeleteHome(homeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHome", reflect.TypeOf((*MockIHomeRepo)(nil).DeleteHome), homeID)
}

// GetHomeByID mocks base method.
func (m *MockIHomeRepo) GetHomeByID(homeID string) (pkg.HomeData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHomeByID", homeID)
	ret0, _ := ret[0].(pkg.HomeData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHomeByID indicates an expected call of GetHomeByID.
func (mr *MockIHomeRepoMockRecorder) GetHomeByID(homeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHomeByID", reflect.TypeOf((*MockIHomeRepo)(nil).GetHomeByID), homeID)
}

// ListUserHome mocks base method.
func (m *MockIHomeRepo) ListUserHome(userID string) ([]pkg.HomeData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserHome", userID)
	ret0, _ := ret[0].([]pkg.HomeData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserHome indicates an expected call of ListUserHome.
func (mr *MockIHomeRepoMockRecorder) ListUserHome(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserHome", reflect.TypeOf((*MockIHomeRepo)(nil).ListUserHome), userID)
}

// UpdateHome mocks base method.
func (m *MockIHomeRepo) UpdateHome(homeID, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHome", homeID, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHome indicates an expected call of UpdateHome.
func (mr *MockIHomeRepoMockRecorder) UpdateHome(homeID, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHome", reflect.TypeOf((*MockIHomeRepo)(nil).UpdateHome), homeID, name)
}

// MockIAccessHomeRepo is a mock of IAccessHomeRepo interface.
type MockIAccessHomeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIAccessHomeRepoMockRecorder
}

// MockIAccessHomeRepoMockRecorder is the mock recorder for MockIAccessHomeRepo.
type MockIAccessHomeRepoMockRecorder struct {
	mock *MockIAccessHomeRepo
}

// NewMockIAccessHomeRepo creates a new mock instance.
func NewMockIAccessHomeRepo(ctrl *gomock.Controller) *MockIAccessHomeRepo {
	mock := &MockIAccessHomeRepo{ctrl: ctrl}
	mock.recorder = &MockIAccessHomeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccessHomeRepo) EXPECT() *MockIAccessHomeRepoMockRecorder {
	return m.recorder
}

// AddOwner mocks base method.
func (m *MockIAccessHomeRepo) AddOwner(userID, homeID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOwner", userID, homeID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOwner indicates an expected call of AddOwner.
func (mr *MockIAccessHomeRepoMockRecorder) AddOwner(userID, homeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOwner", reflect.TypeOf((*MockIAccessHomeRepo)(nil).AddOwner), userID, homeID)
}

// AddUser mocks base method.
func (m *MockIAccessHomeRepo) AddUser(homeID string, access pkg.AccessService) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", homeID, access)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUser indicates an expected call of AddUser.
func (mr *MockIAccessHomeRepoMockRecorder) AddUser(homeID, access interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockIAccessHomeRepo)(nil).AddUser), homeID, access)
}

// DeleteUser mocks base method.
func (m *MockIAccessHomeRepo) DeleteUser(accessID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", accessID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockIAccessHomeRepoMockRecorder) DeleteUser(accessID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockIAccessHomeRepo)(nil).DeleteUser), accessID)
}

// GetInfoAccessByID mocks base method.
func (m *MockIAccessHomeRepo) GetInfoAccessByID(accessID string) (pkg.AccessInfoData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfoAccessByID", accessID)
	ret0, _ := ret[0].(pkg.AccessInfoData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfoAccessByID indicates an expected call of GetInfoAccessByID.
func (mr *MockIAccessHomeRepoMockRecorder) GetInfoAccessByID(accessID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfoAccessByID", reflect.TypeOf((*MockIAccessHomeRepo)(nil).GetInfoAccessByID), accessID)
}

// GetListUserHome mocks base method.
func (m *MockIAccessHomeRepo) GetListUserHome(homeID string) ([]pkg.AccessInfoData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListUserHome", homeID)
	ret0, _ := ret[0].([]pkg.AccessInfoData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListUserHome indicates an expected call of GetListUserHome.
func (mr *MockIAccessHomeRepoMockRecorder) GetListUserHome(homeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListUserHome", reflect.TypeOf((*MockIAccessHomeRepo)(nil).GetListUserHome), homeID)
}

// UpdateLevel mocks base method.
func (m *MockIAccessHomeRepo) UpdateLevel(accessID string, updateAccess pkg.AccessService) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLevel", accessID, updateAccess)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLevel indicates an expected call of UpdateLevel.
func (mr *MockIAccessHomeRepoMockRecorder) UpdateLevel(accessID, updateAccess interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLevel", reflect.TypeOf((*MockIAccessHomeRepo)(nil).UpdateLevel), accessID, updateAccess)
}

// UpdateStatus mocks base method.
func (m *MockIAccessHomeRepo) UpdateStatus(userID string, access pkg.AccessService) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", userID, access)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockIAccessHomeRepoMockRecorder) UpdateStatus(userID, access interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockIAccessHomeRepo)(nil).UpdateStatus), userID, access)
}

// MockIDeviceRepo is a mock of IDeviceRepo interface.
type MockIDeviceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIDeviceRepoMockRecorder
}

// MockIDeviceRepoMockRecorder is the mock recorder for MockIDeviceRepo.
type MockIDeviceRepoMockRecorder struct {
	mock *MockIDeviceRepo
}

// NewMockIDeviceRepo creates a new mock instance.
func NewMockIDeviceRepo(ctrl *gomock.Controller) *MockIDeviceRepo {
	mock := &MockIDeviceRepo{ctrl: ctrl}
	mock.recorder = &MockIDeviceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDeviceRepo) EXPECT() *MockIDeviceRepoMockRecorder {
	return m.recorder
}

// CreateDevice mocks base method.
func (m *MockIDeviceRepo) CreateDevice(homeID string, device pkg.DevicesService, character pkg.DeviceCharacteristicsService, typeCharacter pkg.TypeCharacterService) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDevice", homeID, device, character, typeCharacter)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDevice indicates an expected call of CreateDevice.
func (mr *MockIDeviceRepoMockRecorder) CreateDevice(homeID, device, character, typeCharacter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDevice", reflect.TypeOf((*MockIDeviceRepo)(nil).CreateDevice), homeID, device, character, typeCharacter)
}

// DeleteDevice mocks base method.
func (m *MockIDeviceRepo) DeleteDevice(deviceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevice", deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDevice indicates an expected call of DeleteDevice.
func (mr *MockIDeviceRepoMockRecorder) DeleteDevice(deviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevice", reflect.TypeOf((*MockIDeviceRepo)(nil).DeleteDevice), deviceID)
}

// GetDeviceByID mocks base method.
func (m *MockIDeviceRepo) GetDeviceByID(deviceID string) (pkg.DevicesData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceByID", deviceID)
	ret0, _ := ret[0].(pkg.DevicesData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceByID indicates an expected call of GetDeviceByID.
func (mr *MockIDeviceRepoMockRecorder) GetDeviceByID(deviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceByID", reflect.TypeOf((*MockIDeviceRepo)(nil).GetDeviceByID), deviceID)
}

// GetListDevices mocks base method.
func (m *MockIDeviceRepo) GetListDevices(homeID string) ([]pkg.DevicesData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListDevices", homeID)
	ret0, _ := ret[0].([]pkg.DevicesData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListDevices indicates an expected call of GetListDevices.
func (mr *MockIDeviceRepoMockRecorder) GetListDevices(homeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListDevices", reflect.TypeOf((*MockIDeviceRepo)(nil).GetListDevices), homeID)
}

// MockIHistoryDeviceRepo is a mock of IHistoryDeviceRepo interface.
type MockIHistoryDeviceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIHistoryDeviceRepoMockRecorder
}

// MockIHistoryDeviceRepoMockRecorder is the mock recorder for MockIHistoryDeviceRepo.
type MockIHistoryDeviceRepoMockRecorder struct {
	mock *MockIHistoryDeviceRepo
}

// NewMockIHistoryDeviceRepo creates a new mock instance.
func NewMockIHistoryDeviceRepo(ctrl *gomock.Controller) *MockIHistoryDeviceRepo {
	mock := &MockIHistoryDeviceRepo{ctrl: ctrl}
	mock.recorder = &MockIHistoryDeviceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHistoryDeviceRepo) EXPECT() *MockIHistoryDeviceRepoMockRecorder {
	return m.recorder
}

// CreateDeviceHistory mocks base method.
func (m *MockIHistoryDeviceRepo) CreateDeviceHistory(deviceID string, history pkg.HistoryService) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeviceHistory", deviceID, history)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeviceHistory indicates an expected call of CreateDeviceHistory.
func (mr *MockIHistoryDeviceRepoMockRecorder) CreateDeviceHistory(deviceID, history interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeviceHistory", reflect.TypeOf((*MockIHistoryDeviceRepo)(nil).CreateDeviceHistory), deviceID, history)
}

// GetDeviceHistory mocks base method.
func (m *MockIHistoryDeviceRepo) GetDeviceHistory(deviceID string) ([]pkg.DevicesHistoryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceHistory", deviceID)
	ret0, _ := ret[0].([]pkg.DevicesHistoryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceHistory indicates an expected call of GetDeviceHistory.
func (mr *MockIHistoryDeviceRepoMockRecorder) GetDeviceHistory(deviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceHistory", reflect.TypeOf((*MockIHistoryDeviceRepo)(nil).GetDeviceHistory), deviceID)
}
